name: Firebase CI/CD

on:
  push:
    branches:
      - task4_test  # Run the workflow only when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Step 4: Install Firebase CLI
    - name: Install Firebase CLI
      run: |
        curl -sL https://firebase.tools | bash
        # Make sure it's available in the path
        export PATH=$PATH:/usr/local/bin
        firebase --version

    # Step 5: Build APK or iOS IPA
    - name: Build APK
      run: flutter build apk --release

    

    # Step 6: Authenticate with Firebase using the CI token
    - name: Authenticate with Firebase CLI
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > $HOME/service-account.json
        export FIREBASE_SERVICE_ACCOUNT_KEY=$HOME/service-account.json

      
    # Step 7: Upload APK to Firebase App Distribution
    - name: Upload APK to Firebase App Distribution
      run: |
        firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --release-notes "Automated build from GitHub Actions" \
          --debug

